In [1]:
%pip install numpy
# !pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [62]:
a = np.arange(0, 100, 50)
a

array([ 0, 50])

In [63]:
a = np.arange(0,100,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [64]:
a2 = a.copy() + 1 
a2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [36]:
a3 = a.copy() - 1
a3

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
       33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

array([-1,  2, -1, -1, -1, -1, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [66]:
a4 = a * 2
a4

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196])

In [67]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [69]:
a5 = a.copy() **2
a5

array([   0,    4,   16,   36,   64,  100,  144,  196,  256,  324,  400,
        484,  576,  676,  784,  900, 1024, 1156, 1296, 1444, 1600, 1764,
       1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096,
       4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396,
       7744, 8100, 8464, 8836, 9216, 9604])

In [70]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
b[[0,2,3,4,5]]  = -2
b

array([-2,  2, -2, -2, -2, -2,  7,  8,  9, 10])

In [103]:
b = np.ones(4) +1 
b

array([2., 2., 2., 2.])

In [111]:
d = np.array([1,2,3,4])
d+1

array([2, 3, 4, 5])

In [112]:
d**2

array([ 1,  4,  9, 16])

In [114]:
d - b  # type: ignore

array([-1.,  0.,  1.,  2.])

In [117]:
d*b

array([2., 4., 6., 8.])

In [119]:
c = np.diag([1,2,3,4])
c*c


array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [120]:
print("*************************")
c.dot(c)

*************************


array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [118]:
c = np.diag([1,2,3,4])
print(c*c)
print("*************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


<h3>Element wise comparison of np array<h3>

In [123]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
print(a==b)
a==b

[False  True False  True]


array([False,  True, False,  True])

In [124]:
a>b

array([False, False,  True, False])

<h3>np array comparison<h3>

In [125]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

# check is all the elements are equal or not in both the arrays
np.array_equal(a,b)

False

In [126]:
np.array_equal(a,c)

True

<h3> Logical Operators</h3>

In [127]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [128]:
np.logical_and(a,b) 

array([ True, False, False, False])

<h3> Scientific operations </h3>

In [129]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [131]:
np.log(a)

C:\Users\moham\AppData\Local\Temp\ipykernel_6256\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [132]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

<h3> Playing with Dimensrions/Ranks </h3>

<h4> Reductions </h4>

In [133]:
x = np.array([[1,2,3,4]])
np.sum(x)

10

In [135]:
x = np.array([[1,2],[3,4]])
x


array([[1, 2],
       [3, 4]])

In [136]:
# Column-wise sum of the values
# column is the first dimension of the array

x.sum(axis=0)    

array([4, 6])

In [137]:
# row-wise sum of the values
# row is the second dimension of the array

x.sum(axis=1)

array([3, 7])

In [138]:
y = np.array([1,2,3,4,5,6])
y.min()

1

In [139]:
y.max()

6

In [140]:
y.argmin()

0

In [141]:
y.argmax()

5

<h3> Logical Operations</h3>

In [142]:
np.all([True, True, False])

False

In [143]:
np.any([True, False, False])

True

In [145]:
a = np.zeros((50,50))
np.any(a!=0)

False

In [146]:
np.all(a==a)

True

In [147]:
np.all(a==0)

True

In [6]:
a = np.array([1,2,3,2,4])
b = np.array([2,2,3,4,4])
c = np.array([2,3,3,5,6])

(a<=b).all()

True

In [4]:
(b<=c).all()

True

In [7]:
a<=b

array([ True,  True,  True,  True,  True])

In [8]:
b<=c

array([ True,  True,  True,  True,  True])

In [9]:
a<=c

array([ True,  True,  True,  True,  True])

In [12]:
((a<=b)&(b<=c)).all()

True

<h3> Flattening </h3>

In [13]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [19]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])